TeacherLoadApp/Controllers/DisciplinesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TeacherLoad.Core.DataInterfaces;
using TeacherLoad.Core.Models;
using TeacherLoad.Data.Service;

namespace TeacherLoadApp.Controllers
{
    public class DisciplinesController : Controller
    {
        private readonly IUnitOfWork unitOfWork;

        public DisciplinesController(TeacherLoadContext context)
        {
            unitOfWork = new UnitOfWork(context);
        }
        // GET: Disciplines
        public ActionResult Index()
        {
            var disciplines = unitOfWork.Disciplines.Get(orderBy: q => q.OrderBy(d => d.DisciplineName));
            var isAjax = Request.Headers["X-Requested-With"] == "XMLHttpRequest";
            if (isAjax)
            {
                return PartialView("_Disciplines", disciplines);
            }

            return View("DisciplinesList",disciplines);
        }

        public ActionResult Create()
        {            
            return PartialView("_CreateDiscipline");
        }

        //[ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Create(Discipline discipline)
        {
            if (IsExists(discipline))
            {
                ModelState.AddModelError("DisciplineName", "В базе данных уже существует дисциплина с таким названием");
            }
            else if (ModelState.IsValid)
            {
                unitOfWork.Disciplines.Insert(new Discipline { DisciplineName = discipline.DisciplineName });
                unitOfWork.Save();
                CreateNotification("Дисциплина добавлена!");
                //return RedirectToAction(nameof(Index));
            }
            return PartialView("_CreateDiscipline", discipline);
        }

        [NonAction]
        private void CreateNotification(string message)
        {
            TempData.TryGetValue("Notifications", out object value);
            var notifications = value as List<string> ?? new List<string>();
            notifications.Add(message);
            TempData["Notifications"] = notifications;
        }

        public IActionResult Notifications()
        {
            TempData.TryGetValue("Notifications", out object value);
            var notifications = value as IEnumerable<string> ?? Enumerable.Empty<string>();
            return PartialView("_NotificationsPartial", notifications);
        }

        // GET: Groups/Edit/5
        public ActionResult Edit(int id)
        {
            var discipline = unitOfWork.Disciplines.GetByID(id);
            if (discipline == null)
            {
                return NotFound();
            }
            //return View("EditDiscipline",discipline);            
            return PartialView("_EditDiscipline",discipline);
        }

        private bool IsExists(Discipline discipline)
        {
            return unitOfWork.Disciplines.Get(d => d.DisciplineName == discipline.DisciplineName).Any();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Discipline discipline)
        {
            if (IsExists(discipline))
            {
                ModelState.AddModelError("DisciplineName", "В базе данных уже существует дисциплина с таким названием");
            }
            else if (ModelState.IsValid)
            {
                unitOfWork.Disciplines.Update(discipline);
                unitOfWork.Save();
                CreateNotification("Дисциплина успешно изменена!");
            }            
            return PartialView("_EditDiscipline", discipline);
        }

        // GET: Specialities/Delete/5
        public ActionResult Delete(int id)
        {
            var discipline = unitOfWork.Disciplines.GetByID(id);
            if (discipline == null)
            {
                return NotFound();           
            }            
            return View("DeleteDiscipline", discipline);
        }

        // POST: Specialities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var discipline = unitOfWork.Disciplines.GetByID(id);
            if (discipline != null)
            {
                if (discipline.GroupLoads.Any())
                {
                    ModelState.AddModelError("DisciplineID", "Нельзя удалять дисциплину, пока она есть в нагрузке у преподавателей!");
                    return View("DeleteDiscipline", discipline);
                }
                unitOfWork.Disciplines.Delete(discipline);
                var saved = false;
                while (!saved)
                {
                    try
                    {
                        // Attempt to save changes to the database
                        unitOfWork.Save();
                        saved = true;
                    }
                    catch (DbUpdateConcurrencyException ex)
                    {
                        foreach (var entry in ex.Entries)
                        {
                            if (entry.Entity is Discipline)
                            {
                                if (entry.GetDatabaseValues() == null)
                                    return View("DisciplinesList", unitOfWork.Disciplines.Get(orderBy: x => x.OrderBy(d => d.DisciplineName)));
                            }
                        }
                    }
                }
            }
            return View("DisciplinesList", unitOfWork.Disciplines.Get(orderBy: x => x.OrderBy(d => d.DisciplineName)));
        }     
    }
}

TeacherLoadApp/Views/Disciplines/DeleteDiscipline.cshtml
@model TeacherLoad.Core.Models.Discipline

<h3>Вы уверены, что хотите удалить запись?</h3>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DisciplineName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DisciplineName)
        </dd>
    </dl>
    <form asp-action="Delete">
        <div style="margin-bottom: 20px;">
            <input type="hidden" asp-for="DisciplineID" />
            <span asp-validation-for="DisciplineID" class="text-danger"></span>
        </div>
        <input type="submit" value="Удалить" class="btn btn-danger" />
        <a class="btn btn-primary" asp-action="Index">Отменить</a>
    </form>
</div>

TeacherLoadApp/Views/Disciplines/DisciplinesList.cshtml
@model IEnumerable<TeacherLoad.Core.Models.Discipline>

@{
    ViewData["Title"] = "Дисциплины";
}

<h2>Дисциплины</h2>

<div class="modal fade" id="add-discipline" tabindex="-1" role="dialog" 
        aria-labelledby="addDisciplineLabel" aria-hidden="true">
    <div id="dialog-content" class="modal-dialog" role="document"></div>
</div>
<p>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#add-discipline"
            data-url="@Url.Action("Create")">
        Добавить дисциплину
    </button>
</p>

@{await Html.RenderPartialAsync("_Disciplines", Model);}

TeacherLoadApp/Views/Disciplines/_CreateDiscipline.cshtml
@model TeacherLoad.Core.Models.Discipline

<div class="modal-content">
    <div class="modal-header">
        <h3 class="modal-title" id="addDisciplineLabel">Добавление дисциплины</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <form id="create-form" asp-action="Create">       
        @Html.ValidationSummary()
        <div class="modal-body">
            <input name="IsValid" type="hidden" value="@ViewData.ModelState.IsValid.ToString()" />
            <div class="form-group">
                <input asp-for="DisciplineName" required class="form-control" name="DisciplineName"
                       placeholder="Дисциплина" autofocus />
                <span asp-validation-for="DisciplineName" class="text-danger"></span>
            </div>
        </div>
        <div id="notification" data-url="@Url.Action("Notifications", "Disciplines")"></div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
            <button type="submit" class="btn btn-primary" data-save="modal">Сохранить</button>
        </div>
    </form>
</div>
       

TeacherLoadApp/Views/Disciplines/_Disciplines.cshtml
@model IEnumerable<TeacherLoad.Core.Models.Discipline>

    
    <table class="table table-hover" id="disciplines" data-url="@Url.Action("Index")">
        <thead class="thead-light">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.DisciplineName)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.DisciplineName)
                    </td>
                    <td>
                        <button type="button" class="btn btn-success" data-toggle="modal" data-target="#add-discipline"
                                data-url="@Url.Action("Edit","Disciplines", new { id = item.DisciplineID })">
                            <span class="btn-label"><i class="glyphicon glyphicon-pencil"></i></span>
                            Изменить
                        </button>  
                        <a class="btn btn-danger" href="@Url.Action("Delete","Disciplines", new { id = item.DisciplineID })">
                            <span class="btn-label"><i class="glyphicon glyphicon-trash"></i></span>
                            Удалить
                        </a>                        
                    </td>
                </tr>
            }
        </tbody>
    </table>

TeacherLoadApp/Views/Disciplines/_EditDiscipline.cshtml
@model TeacherLoad.Core.Models.Discipline

<div class="modal-content">
    <div class="modal-header">
        <h3 class="modal-title" id="addDisciplineLabel">Изменение дисциплины</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <form id="create-form" asp-action="Edit">        
        @Html.ValidationSummary()
        <input type="hidden" asp-for="DisciplineID" />
        <div class="modal-body">
            <input name="IsValid" type="hidden" value="@ViewData.ModelState.IsValid.ToString()" />
            <div class="form-group">
                <input asp-for="DisciplineName" required class="form-control" name="DisciplineName"
                       placeholder="Дисциплина" autofocus />
                <span asp-validation-for="DisciplineName" class="text-danger"></span>
            </div>
        </div>
        <div id="notification" data-url="@Url.Action("Notifications", "Disciplines")"></div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
            <button type="submit" class="btn btn-primary" data-save="modal">Сохранить</button>
        </div>
    </form>
</div>