TeacherLoadApp/Controllers/GroupsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using TeacherLoad.Core.Models;
using TeacherLoad.Data.Service;
using TeacherLoadApp.Models;
using System.Linq;
using TeacherLoad.Core.DataInterfaces;
using TeacherLoadApp.Models.Groups;

namespace TeacherLoadApp.Controllers
{
    public class GroupsController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        public GroupsController(TeacherLoadContext context)
        {
            unitOfWork = new UnitOfWork(context);
        }

        // GET: Groups
        public IActionResult Index(int studyYear = 1)
        {
            var groups = unitOfWork.Groups.Get(g => g.StudyYear == studyYear, includeProperties: "Speciality")
                                   .OrderBy(g => g.GroupNumber);
            var groupedGroups = groups.GroupBy(x => x.Speciality.SpecialityName)
                  .Select(g => new GroupingVM<Group> { Key = g.Key, Values = g.ToList() }).ToList();

            var isAjax = Request.Headers["X-Requested-With"] == "XMLHttpRequest";
            if (isAjax)
            {
                return PartialView("GroupsListPartial", new GroupsIndexVM
                {
                    StudyGroup = groups.FirstOrDefault(),
                    GroupedStudyGroups = groupedGroups
                });
            }

            var model = new GroupsIndexVM
            {
                StudyGroup = groups.FirstOrDefault(),
                Years = new SelectList(Enumerable.Range(1, 4), studyYear),
                GroupedStudyGroups = groupedGroups
            };

            return View("GroupsList", model);
        }

        public IActionResult GroupDisciplines(string id)
        {
            var isAjax = Request.Headers["X-Requested-With"] == "XMLHttpRequest";
            if (isAjax)
            {
                if (id == null)
                    return View(new GroupDisciplinesVM()
                    {
                        Groups = GetGroupsList(id),
                        GroupDisciplines = new List<GroupDisciplinesVMItem>()
                    });
                return PartialView("_GroupDisciplines", GetModels(id).GroupDisciplines);
            }
            return View("GroupDisciplines", GetModels(id));
        }        

        private SelectList GetGroupsList(string selected = null)
        {
            return new SelectList(unitOfWork.Groups.Get(), "GroupNumber", "GroupNumber", selected);
        }
        

        private GroupDisciplinesVM GetModels(string id)
        {
            var items = unitOfWork.GroupLoads.GetDisciplinesByGroup(id);
            var model = new GroupDisciplinesVM();
            var modelItems = new List<GroupDisciplinesVMItem>();
            model.GroupDisciplines = modelItems;
            if (items.Any())
            {
                model.Groups = new SelectList(unitOfWork.Groups.Get(/*g => g.StudyYear == items.First().StudyYear*/),
                    "GroupNumber", "GroupNumber", id);
            }
            else
            {
                model.Groups = GetGroupsList();
            }
            foreach (GroupLoad groupLoad in items)
            {
                GroupDisciplinesVMItem item = new GroupDisciplinesVMItem
                {
                    ClassType = groupLoad.GroupStudies.GroupClassName,
                    Discipline = groupLoad.Discipline.DisciplineName,
                    TeacherName = groupLoad.Teacher.FullName
                };
                modelItems.Add(item);
            }
            return model;
        }

        // GET: Groups/Create
        public IActionResult Create()
        {
            var model = new StudyGroupVM
            {                
                Specialities = GetSpecialitiesList(),
                Group = new Group()
            };           
            return View("CreateGroup",model);
        }

        // POST: Groups/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(StudyGroupVM groupVM)
        {
            if (ModelState.IsValid)
            {
                unitOfWork.Groups.Insert(groupVM.Group);
                unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            groupVM.Specialities = GetSpecialitiesList(groupVM.Group.SpecialityCode);
            return View("CreateGroup",groupVM);
        }

        // GET: Groups/Edit/5
        public IActionResult Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var group = unitOfWork.Groups.GetByID(id);
            if (group == null)
            {
                return NotFound();
            }
            var model = new StudyGroupVM
            {
                Group = group,
                Specialities = GetSpecialitiesList(group.SpecialityCode)
            };
            return View("EditGroup", model);
        }

        // POST: Groups/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(StudyGroupVM groupVM)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    unitOfWork.Groups.Update(groupVM.Group);
                    unitOfWork.Save();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GroupExists(groupVM.Group.GroupNumber))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            var model = new StudyGroupVM
            {
                Group = groupVM.Group,
                Specialities = GetSpecialitiesList(groupVM.Group.SpecialityCode)
            };
            return View("EditGroup",model);
        }

        // GET: Groups/Delete/5
        public IActionResult Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @group = unitOfWork.Groups.GetByID(id);
            if (@group == null)
            {
                return NotFound();
            }

            return View("DeleteGroup",@group);
        }

        // POST: Groups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(string id)
        {
            var group = unitOfWork.Groups.GetByID(id);           
            unitOfWork.Groups.Delete(group);
            unitOfWork.Save();
            return RedirectToAction(nameof(Index));
        }        

        private SelectList GetSpecialitiesList(string selected = null)
        {
            return new SelectList(unitOfWork.Specialities.Get(), "Code", "NameWithCode", selected);
        }

        private bool GroupExists(string id)
        {
            return unitOfWork.Groups.GetByID(id) != null;
        }
    }
}

TeacherLoadApp/Controllers/PositionsController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TeacherLoad.Core.DataInterfaces;
using TeacherLoad.Core.Models;
using TeacherLoad.Data.Service;

namespace TeacherLoadApp.Controllers
{
    public class PositionsController : Controller
    {
        private readonly IUnitOfWork unitOfWork;

        public PositionsController(TeacherLoadContext context)
        {
            unitOfWork = new UnitOfWork(context);
        }
        // GET: Positions
        public ActionResult Index()
        {
            var positions = unitOfWork.Positions.Get(orderBy: q => q.OrderBy(p => p.PositionName));
            return View("PositionsList", positions);
        }

        public IActionResult Create()
        {
            return View("CreatePosition");
        }

        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Position position)
        {
            if (unitOfWork.Positions.Get(p => p.PositionName == position.PositionName).Any())
            {
                ModelState.AddModelError("PositionName", "Такая должность уже существует!");
            }
            else if (ModelState.IsValid)
            {
                unitOfWork.Positions.Insert(position);
                unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            return View("CreatePosition", position);
        }

        // GET: Groups/Edit/5
        public IActionResult Edit(int id)
        {
            var position = unitOfWork.Positions.GetByID(id);
            if (position == null)
            {
                return NotFound();
            }
            return View("EditPosition", position);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Position position)
        {
            if (id != position.PositionID)
            {
                return NotFound();
            }
            if (unitOfWork.Positions.Get(p => p.PositionName == position.PositionName).Any())
            {
                ModelState.AddModelError("PositionName", "Такая должность уже существует!");
            }
            else if (ModelState.IsValid)
            {
                try
                {
                    unitOfWork.Positions.Update(position);
                    unitOfWork.Save();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (unitOfWork.Positions.GetByID(id) != null)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View("EditPosition", position);
        }

        // GET: Specialities/Delete/5
        public ActionResult Delete(int id)
        {
            var position = unitOfWork.Positions.GetByID(id);
            if (position == null)
            {
                return NotFound();
            }

            return View("DeletePosition", position);
        }

        // POST: Specialities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var position = unitOfWork.Positions.GetByID(id);
            if (position.Teachers.Any())
            {
                ModelState.AddModelError("PositionID", "Нельзя удалять должность, пока на ней работают сотрудники!");
                return View("DeletePosition", position);
            }
            unitOfWork.Positions.Delete(position);
            unitOfWork.Save();
            return RedirectToAction(nameof(Index));
        }
    }
}

TeacherLoadApp/Controllers/TeachersController.cs
using System.Data;
using System.Diagnostics;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TeacherLoad.Core.DataInterfaces;
using TeacherLoad.Core.Models;
using TeacherLoad.Data.Service;
using TeacherLoadApp.Models;

namespace TeacherLoadApp.Controllers
{
    public class TeachersController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        public TeachersController(TeacherLoadContext context)
        {
            unitOfWork = new UnitOfWork(context);
        }

        public IActionResult Index()
        {
            var teachers = unitOfWork.Teachers.GetAll().OrderBy(t => t.LastName);             
            return View("TeachersList",teachers);
        }

        public IActionResult Create()
        {
            PopulateDropDownLists();
            return View("CreateTeacher");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Teacher teacher)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    unitOfWork.Teachers.Insert(teacher);
                    unitOfWork.Save();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException /* dex */)
            {
                //Log the error (uncomment dex variable name after DataException and add a line here to write a log.)
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
            }
            PopulateDropDownLists(teacher.DepartmentID, teacher.PositionID);
            return View("CreateTeacher", teacher);
        }

        public IActionResult Edit(int id)
        {
            Teacher teacher = unitOfWork.Teachers.GetByID(id);
            PopulateDropDownLists(teacher.DepartmentID,teacher.PositionID);
            return View("EditTeacher",teacher);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit([Bind("TeacherID,FirstName,LastName,Patronym,DepartmentID,PositionID")]
         Teacher teacher)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    unitOfWork.Teachers.Update(teacher);
                    unitOfWork.Save();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException /* dex */)
            {
                //Log the error (uncomment dex variable name after DataException and add a line here to write a log.)
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
            }           
            return View("EditTeacher",teacher);
        }

        public IActionResult Delete(int id)
        {
            Teacher teacher = unitOfWork.Teachers.GetByID(id);
            return View("DeleteTeacher",teacher);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            Teacher teacher = unitOfWork.Teachers.GetByID(id);
            unitOfWork.Teachers.Delete(id);
            unitOfWork.Save();
            return RedirectToAction("Index");
        }       

        private void PopulateDropDownLists(object selectedDepartment = null,object selectedPosition = null)
        {
            var departmentsQuery = unitOfWork.Departments.Get().OrderBy(d => d.DepartmentName);
            ViewBag.DepartmentID = new SelectList(departmentsQuery, "DepartmentID", "DepartmentName", selectedDepartment);
            var positionsQuery = unitOfWork.Positions.Get(orderBy: q => q.OrderBy(p => p.PositionName));
            ViewBag.PositionID = new SelectList(positionsQuery, "PositionID", "PositionName", selectedPosition);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TeacherLoadApp/Views/Home/Create.cshtml
@model TeacherLoad.Core.Models.Teacher

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Teacher</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Patronym" class="control-label"></label>
                <input asp-for="Patronym" class="form-control" />
                <span asp-validation-for="Patronym" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepartmentID" class="control-label"></label>
                <select asp-for="DepartmentID" class ="form-control" asp-items="ViewBag.DepartmentID"></select>
            </div>
            <div class="form-group">
                <label asp-for="PositionID" class="control-label"></label>
                <select asp-for="PositionID" class ="form-control" asp-items="ViewBag.PositionID"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TeacherLoadApp/Views/Home/Delete.cshtml
@model TeacherLoad.Core.Models.Teacher

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Teacher</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Patronym)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Patronym)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Department)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Department.DepartmentName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Position)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Position.PositionName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="TeacherID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TeacherLoadApp/Views/Home/Details.cshtml
@model TeacherLoad.Core.Models.Teacher

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Teacher</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Patronym)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Patronym)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Department)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Department.DepartmentName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Position)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Position.PositionName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.TeacherID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

TeacherLoadApp/Views/Home/Edit.cshtml
@model TeacherLoad.Core.Models.Teacher

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Teacher</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="TeacherID" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Patronym" class="control-label"></label>
                <input asp-for="Patronym" class="form-control" />
                <span asp-validation-for="Patronym" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepartmentID" class="control-label"></label>
                <select asp-for="DepartmentID" class="form-control" asp-items="ViewBag.DepartmentID"></select>
                <span asp-validation-for="DepartmentID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PositionID" class="control-label"></label>
                <select asp-for="PositionID" class="form-control" asp-items="ViewBag.PositionID"></select>
                <span asp-validation-for="PositionID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TeacherLoadApp/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<TeacherLoad.Core.Models.ApplicationUser> SignInManager
@inject UserManager<TeacherLoad.Core.Models.ApplicationUser> UserManager
@{
    ViewData["Title"] = "Нагрузка кафедры";
}

<style>
    body {
        background-color: #F5F5F5;
        font-family: 'Coda', cursive;
    }
</style>
@if (User.IsInRole("Администратор"))
{
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <a href="@Url.Action("Index", "Teachers")">
                        <img src="@Url.Content("~/images/professor.svg")" class="card-img-top card-icon" />
                        <p class="card-text">Просмотр и управление преподавателями</p>
                    </a>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <a href="@Url.Action("Index", "Positions")">
                        <img src="@Url.Content("~/images/position.svg")" class="card-img-top card-icon" />
                        <p class="card-text">Просмотр и управление должностями<p>
                    </a>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <a href="@Url.Action("Index", "Groups")">
                        <img src="@Url.Content("~/images/student.svg")" class="card-img-top card-icon" />
                        <p class="card-text">Просмотр и управление учебными группами</p>
                    </a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <a href="@Url.Action("Index", "Disciplines")">
                        <img src="@Url.Content("~/images/books.svg")" class="card-img-top card-icon" />
                        <p class="card-text">Просмотр и управление дисциплинами<p>
                    </a>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <a href="@Url.Action("Index", "GroupLoads")">
                        <img src="@Url.Content("~/images/classroom.svg")" class="card-img-top card-icon" />
                        <p class="card-text">Просмотр и управление групповой нагрузкой</p>
                    </a>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <a href="@Url.Action("Index", "PersonalLoads")">
                        <img src="@Url.Content("~/images/interview.svg")" class="card-img-top card-icon" />
                        <p class="card-text">Просмотр и управление индивидуальной нагрузкой</p>
                    </a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <a href="@Url.Action("Index", "Specialities")">
                        <img src="@Url.Content("~/images/worker.svg")" class="card-img-top card-icon" />
                        <p class="card-text">Просмотр и управление специальностями<p>
                    </a>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <a href="@Url.Action("Index", "GroupStudies")">
                        <img src="@Url.Content("~/images/group-class.svg")" class="card-img-top card-icon" />
                        <p class="card-text">Просмотр и управление групповыми занятиями<p>
                    </a>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <a href="@Url.Action("Index", "IndividualStudies")">
                        <img src="@Url.Content("~/images/personal-class.svg")" class="card-img-top card-icon" />
                        <p class="card-text">Просмотр и управление индивидуальными занятиями<p>
                    </a>
                </div>
            </div>
        </div>
    </div>
}

TeacherLoadApp/Views/Home/ReportView.cshtml
<link href="~/node_modules/jquery-ui-dist/jquery-ui.min.css" rel="stylesheet" />

<script src="~/node_modules/jquery/dist/jquery.min.js"></script>
<script src="~/node_modules/jquery-ui-dist/jquery-ui.min.js"></script>

<script src="~/node_modules/knockout/build/output/knockout-latest.js"></script>

<script src="~/node_modules/cldrjs/dist/cldr.js"></script>
<script src="~/node_modules/cldrjs/dist/cldr/event.js"></script>
<script src="~/node_modules/cldrjs/dist/cldr/supplemental.js"></script>
<script src="~/node_modules/cldrjs/dist/cldr/unresolved.js"></script>

<script src="~/node_modules/globalize/dist/globalize.js"></script>
<script src="~/node_modules/globalize/dist/globalize/currency.js"></script>
<script src="~/node_modules/globalize/dist/globalize/message.js"></script>
<script src="~/node_modules/globalize/dist/globalize/number.js"></script>
<script src="~/node_modules/globalize/dist/globalize/date.js"></script>

<script src="~/node_modules/devextreme/dist/js/dx.all.js"></script>
<link href="~/node_modules/devextreme/dist/css/dx.common.css" rel="stylesheet" />
<link href="~/node_modules/devextreme/dist/css/dx.light.css" rel="stylesheet" />

<!-- If your application contains the Document Viewer only -->
<script src="~/node_modules/@@devexpress/analytics-core/dist/js/dx-analytics-core.js"></script>
<script src="~/node_modules/devexpress-reporting/dist/js/dx-webdocumentviewer.js"></script>
<link href="~/node_modules/@@devexpress/analytics-core/dist/css/dx-analytics.common.css" rel="stylesheet" />
<link href="~/node_modules/@@devexpress/analytics-core/dist/css/dx-analytics.light.css" rel="stylesheet" />
<link href="~/node_modules/devexpress-reporting/dist/css/dx-webdocumentviewer.css" rel="stylesheet" />

@Html.DevExpress().WebDocumentViewer("WebDocumentViewer").Height("1000px").Bind("SummaryReport")