TeacherLoadApp/Models/PersonalLoad/PersonalLoadVM.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using TeacherLoad.Core.Models;

namespace TeacherLoadApp.Models
{
    public class PersonalLoadVM
    {
        public PersonalLoad PersonalLoad { get; set; }
        public SelectList Teachers { get; set; }
        public SelectList Classes { get; set; }        
    }
}

TeacherLoadApp/Models/PersonalLoad/TeacherPersonalLoadVM.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using TeacherLoad.Core.Models;

namespace TeacherLoadApp.Models
{
    public class TeacherPersonalLoadVM
    {
       public SelectList PersonalStudies { get; set; }
       public List<GroupingVM<PersonalLoad>> GroupedLoads { get; set; }
       public List<PersonalLoad> PersonalLoads { get; set; }
    }
}

TeacherLoadApp/Controllers/PersonalLoadsController.cs
using System.Collections.Generic;
using System.Data;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TeacherLoad.Core.DataInterfaces;
using TeacherLoad.Core.Models;
using TeacherLoad.Data.Service;
using TeacherLoadApp.Models;

namespace TeacherLoadApp.Controllers
{
    public class PersonalLoadsController : Controller
    {
        private readonly IUnitOfWork unitOfWork;

        public PersonalLoadsController(TeacherLoadContext context)
        {
            unitOfWork = new UnitOfWork(context);
        }

        // GET: PersonalLoads
        public ActionResult Index()
        {
            var loads = unitOfWork.PersonalLoads.GetAll().OrderBy(pl => pl.Teacher.LastName);
            var classTypes = new SelectList(unitOfWork.IndividualStudies.GetAll(), "IndividualClassID", "IndividualClassName");

            List<GroupingVM<PersonalLoad>> grouped = loads.GroupBy(x => x.Teacher.FullName)
                .Select(g => new GroupingVM<PersonalLoad> { Key = g.Key, Values = g.ToList() }).ToList();

            var model = new TeacherPersonalLoadVM
            {
                PersonalStudies = classTypes,
                PersonalLoads = loads.ToList(),
                GroupedLoads = grouped
            };
            return View("PersonalLoadsList",model);
        }

        public IActionResult TeacherLoadByClassType(int classID)
        {
            var loads = classID != 0 ? unitOfWork.PersonalLoads.Get(pl => pl.IndividualClassID == classID
                , q => q.OrderBy(pl => pl.Teacher.LastName),"Teacher") : unitOfWork.PersonalLoads.GetAll().OrderBy(pl => pl.Teacher.LastName);

            List<GroupingVM<PersonalLoad>> grouped = loads.GroupBy(x => x.Teacher.FullName)
                .Select(g => new GroupingVM<PersonalLoad>{ Key=g.Key, Values = g.ToList() }).ToList();
            
            var classTypes = new SelectList(unitOfWork.IndividualStudies.GetAll(), "IndividualClassID", "IndividualClassName", classID);
            
            return PartialView("_PersonalLoad",grouped);
        }

        public int CalculateHours(int classID,int count)
        {
            IndividualStudies studyType = unitOfWork.IndividualStudies.GetByID(classID);
            return studyType.VolumeByPerson * count;
        }

        // GET: GroupLoads/Create
        public ActionResult Create()
        {
            var model = BuildModel();
            return View("CreatePersonalLoad",model);
        }

        // POST: GroupLoads/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PersonalLoadVM loadModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    unitOfWork.PersonalLoads.Insert(loadModel.PersonalLoad);
                    unitOfWork.Save();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException /* dex */)
            {
                //Log the error (uncomment dex variable name after DataException and add a line here to write a log.)
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
            }
            var model = BuildModel(loadModel.PersonalLoad);
            return View("CreatePersonalLoad",model);
        }

        private PersonalLoadVM BuildModel(PersonalLoad personalLoad = null)
        {
            if (personalLoad == null)
                personalLoad = new PersonalLoad();

            return new PersonalLoadVM
            {
                PersonalLoad = personalLoad,
                Teachers = new SelectList(unitOfWork.Teachers.GetAll(), "TeacherID", "FullName", personalLoad.TeacherID),
                Classes = new SelectList(unitOfWork.IndividualStudies.GetAll(), "IndividualClassID", "IndividualClassName", personalLoad.IndividualClassID)
            };            
        }     

        // GET: GroupLoads/Edit/5
        public ActionResult Edit(int id)
        {
            var load = unitOfWork.PersonalLoads.GetByID(id);
            if (load == null)
            {
                return NotFound();
            }
            var model = BuildModel(load);
            return View("EditPersonalLoad",model);
        }

        // POST: GroupLoads/Edit/5
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public ActionResult EditConfirmed(PersonalLoadVM load)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    unitOfWork.PersonalLoads.Update(load.PersonalLoad);
                    unitOfWork.Save();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException /* dex */)
            {
                //Log the error (uncomment dex variable name after DataException and add a line here to write a log.)
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
            }
            return View("EditPersonalLoad",BuildModel(load.PersonalLoad));
        }

        // GET: GroupLoads/Delete/5
        public ActionResult Delete(int id)
        {
            var load = unitOfWork.PersonalLoads.GetByID(id);
            return View("DeletePersonalLoad",load);
        }

        // POST: GroupLoads/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var load = unitOfWork.PersonalLoads.GetByID(id);
            unitOfWork.PersonalLoads.Delete(load);
            unitOfWork.Save();
            return RedirectToAction("Index");
        }        
    }
}

TeacherLoadApp/Views/PersonalLoads/CreatePersonalLoad.cshtml
@model TeacherLoadApp.Models.PersonalLoadVM

@{
    ViewData["Title"] = "Индивидуальная нагрузка";
}

<h2>Добавление индивидуальной нагрузки</h2>
<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @{ await Html.RenderPartialAsync("_EditPersonalLoad", Model);}
        </form>
    </div>
</div>

@section scripts {
    <script type="text/javascript">
        $(document).ready(() => calculate('@Url.Action("CalculateHours")'));    
    </script>
}

TeacherLoadApp/Views/PersonalLoads/DeletePersonalLoad.cshtml
@model TeacherLoad.Core.Models.PersonalLoad

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PersonalLoad</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StudentsCount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.StudentsCount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Teacher)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Teacher.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IndividualStudies)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IndividualStudies.IndividualClassName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="TeacherID" />
        <input type="hidden" asp-for="IndividualClassID" />
        <input type="submit" value="Сохранить" class="btn btn-success" />
        <a class="btn btn-primary" asp-action="Index">Отменить</a>
    </form>
</div>

TeacherLoadApp/Views/PersonalLoads/EditPersonalLoad.cshtml
@model TeacherLoadApp.Models.PersonalLoadVM

@{
    ViewData["Title"] = "Индивидуальная нагрузка";
}

<h2>Редактирование индивидуальной нагрузки</h2>
<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PersonalLoad.PersonalLoadID" />
            @{ await Html.RenderPartialAsync("_EditPersonalLoad", Model);}
        </form>
    </div>
</div>

@section scripts {
    <script type="text/javascript">
        $(document).ready(() => calculate('@Url.Action("CalculateHours")'));   
    </script>
}

TeacherLoadApp/Views/PersonalLoads/EditPersonalLoadPartial.cshtml
@model TeacherLoadApp.Models.PersonalLoadVM

<div class="form-group">
    <label asp-for="PersonalLoad.TeacherID" class="control-label"></label>
    <select asp-for="PersonalLoad.TeacherID" class="form-control" asp-items="Model.Teachers"></select>
</div>
<div class="form-group">
    <label asp-for="PersonalLoad.IndividualClassID" class="control-label"></label>
    <select onchange="calculate('@Url.Action("CalculateHours")')" id="classType" asp-for="PersonalLoad.IndividualClassID" class="form-control" asp-items="Model.Classes"></select>
</div>
<div class="form-group">
    <label asp-for="PersonalLoad.StudentsCount" class="control-label"></label>
    <input onclick="calculate('@Url.Action("CalculateHours")')" 
           onchange="calculate('@Url.Action("CalculateHours")')" 
           id="studentCount" type="number" min="1" max="40" asp-for="PersonalLoad.StudentsCount" class="form-control" />
    <span asp-validation-for="PersonalLoad.StudentsCount" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="PersonalLoad.TotalVolume" class="control-label"></label>
    <input readonly="readonly" id="totalVolume" asp-for="PersonalLoad.TotalVolume" class="form-control" />
</div>
<div class="form-group">
    <input type="submit" value="Сохранить" class="btn btn-success" />
    <a class="btn btn-primary" asp-action="Index">Отменить</a>
</div>

TeacherLoadApp/Views/PersonalLoads/PersonalLoadPartial.cshtml
@model List<TeacherLoadApp.Models.GroupingVM<TeacherLoad.Core.Models.PersonalLoad>>


@foreach (var group in Model)
{
    <tr>
        <th colspan="5" style="background-color: #ADD8E6;
    border-color: #dee2e6;">@group.Key</th>
</tr>
    foreach (var load in group.Values)
    {
    <tr>       
        <td>
            @Html.DisplayFor(modelItem => load.IndividualStudies.IndividualClassName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => load.StudentsCount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => load.TotalVolume)
        </td>
        <td>
            @{ await Html.RenderPartialAsync("ButtonPartial", ViewData["id"] = load.PersonalLoadID);}
            @*<a class="btn-sm btn-success" href="@Url.Action("Edit", "PersonalLoads", new { teacherID = load.TeacherID, classID = load.IndividualClassID })">
                <span class="btn-label"><i class="glyphicon glyphicon-pencil"></i></span>
                Редактировать
            </a>
            <a class="btn-sm btn-danger" style="margin-left: 10px;" href="@Url.Action("Delete", "PersonalLoads", new { teacherID = load.TeacherID, classID = load.IndividualClassID })">
                <span class="btn-label"><i class="glyphicon glyphicon-trash"></i></span>
                Удалить
            </a>*@
        </td>
    </tr>
    }
}

TeacherLoadApp/Views/PersonalLoads/PersonalLoadsList.cshtml
@model TeacherLoadApp.Models.TeacherPersonalLoadVM

@{
    ViewData["Title"] = "Индивидуальная нагрузка";
}

<h2>Индивидуальная нагрузка</h2>

<p>
    <a class="btn btn-primary" asp-action="Create">Добавить индивидуальную нагрузку</a>
    <div class="form-inline" style="margin: 20px auto;">
        <label class="control-label">Вид занятий:</label>
        @Html.DropDownList("IndividualClassID", Model.PersonalStudies,"Все", new { @class = "form-control selected-class" })
    </div>
</p>

<table class="table table-hover">
    <thead class="thead-light">
        <tr>
            @*<th>
                @Html.DisplayNameFor(model => model.PersonalLoads[0].Teacher.FullName)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.PersonalLoads[0].IndividualStudies)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PersonalLoads[0].StudentsCount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PersonalLoads[0].TotalVolume)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody id="table-body">
        @{ await Html.RenderPartialAsync("_PersonalLoad", Model.GroupedLoads);}
    </tbody>
</table>

    @section scripts{
        <script type="text/javascript">
    $(document).ready(function () {
        $(".selected-class").change(function () {
            $.ajax({
                type: 'GET',
                url: '@Url.Action("TeacherLoadByClassType")',
                data: { classID: $(".selected-class").val() },
                success: function (data) {
                    $("#table-body").html(data);
                }
            });
        });
    });
        </script>
    }

TeacherLoadApp/Views/PersonalLoads/TotalVolumePartial.cshtml
@model TeacherLoad.Core.Models.PersonalLoad

<div id="totalVolume" class="form-group">
    <label asp-for="TotalVolume" class="control-label"></label>
    <input id="totalVolume" asp-for="TotalVolume" class="form-control" />
</div>

TeacherLoadApp/Views/PersonalLoads/_EditPersonalLoad.cshtml
@model TeacherLoadApp.Models.PersonalLoadVM

<div class="form-group">
    <label asp-for="PersonalLoad.TeacherID" class="control-label"></label>
    <select asp-for="PersonalLoad.TeacherID" class="form-control" asp-items="Model.Teachers"></select>
</div>
<div class="form-group">
    <label asp-for="PersonalLoad.IndividualClassID" class="control-label"></label>
    <select onchange="calculate('@Url.Action("CalculateHours")')" id="classType" asp-for="PersonalLoad.IndividualClassID" class="form-control" asp-items="Model.Classes"></select>
</div>
<div class="form-group">
    <label asp-for="PersonalLoad.StudentsCount" class="control-label"></label>
    <input onclick="calculate('@Url.Action("CalculateHours")')" 
           onchange="calculate('@Url.Action("CalculateHours")')" 
           id="studentCount" type="number" min="1" max="40" asp-for="PersonalLoad.StudentsCount" class="form-control" />
    <span asp-validation-for="PersonalLoad.StudentsCount" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="PersonalLoad.TotalVolume" class="control-label"></label>
    <input readonly="readonly" id="totalVolume" asp-for="PersonalLoad.TotalVolume" class="form-control" />
</div>
<div class="form-group">
    <input type="submit" value="Сохранить" class="btn btn-success" />
    <a class="btn btn-primary" asp-action="Index">Отменить</a>
</div>

TeacherLoadApp/Views/PersonalLoads/_PersonalLoad.cshtml
@model List<TeacherLoadApp.Models.GroupingVM<TeacherLoad.Core.Models.PersonalLoad>>


@foreach (var group in Model)
{
    <tr>
        <th colspan="5" style="background-color: #ADD8E6;
    border-color: #dee2e6;">@group.Key</th>
</tr>
    foreach (var load in group.Values)
    {
    <tr>       
        <td>
            @Html.DisplayFor(modelItem => load.IndividualStudies.IndividualClassName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => load.StudentsCount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => load.TotalVolume)
        </td>
        <td>
            @{ await Html.RenderPartialAsync("ButtonPartial", ViewData["id"] = load.PersonalLoadID);}
            @*<a class="btn-sm btn-success" href="@Url.Action("Edit", "PersonalLoads", new { teacherID = load.TeacherID, classID = load.IndividualClassID })">
                <span class="btn-label"><i class="glyphicon glyphicon-pencil"></i></span>
                Редактировать
            </a>
            <a class="btn-sm btn-danger" style="margin-left: 10px;" href="@Url.Action("Delete", "PersonalLoads", new { teacherID = load.TeacherID, classID = load.IndividualClassID })">
                <span class="btn-label"><i class="glyphicon glyphicon-trash"></i></span>
                Удалить
            </a>*@
        </td>
    </tr>
    }
}