TeacherLoadApp/Controllers/GroupsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using TeacherLoad.Core.Models;
using TeacherLoad.Data.Service;
using TeacherLoadApp.Models;
using System.Linq;
using TeacherLoad.Core.DataInterfaces;
using TeacherLoadApp.Models.Groups;

namespace TeacherLoadApp.Controllers
{
    public class GroupsController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        public GroupsController(TeacherLoadContext context)
        {
            unitOfWork = new UnitOfWork(context);
        }

        // GET: Groups
        public IActionResult Index(int studyYear = 1)
        {
            var groups = unitOfWork.Groups.Get(g => g.StudyYear == studyYear, includeProperties: "Speciality")
                                   .OrderBy(g => g.GroupNumber);
            var groupedGroups = groups.GroupBy(x => x.Speciality.SpecialityName)
                  .Select(g => new GroupingVM<Group> { Key = g.Key, Values = g.ToList() }).ToList();

            var isAjax = Request.Headers["X-Requested-With"] == "XMLHttpRequest";
            if (isAjax)
            {
                return PartialView("GroupsListPartial", new GroupsIndexVM
                {
                    StudyGroup = groups.FirstOrDefault(),
                    GroupedStudyGroups = groupedGroups
                });
            }

            var model = new GroupsIndexVM
            {
                StudyGroup = groups.FirstOrDefault(),
                Years = new SelectList(Enumerable.Range(1, 4), studyYear),
                GroupedStudyGroups = groupedGroups
            };

            return View("GroupsList", model);
        }

        public IActionResult GroupDisciplines(string id)
        {
            var isAjax = Request.Headers["X-Requested-With"] == "XMLHttpRequest";
            if (isAjax)
            {
                if (id == null)
                    return View(new GroupDisciplinesVM()
                    {
                        Groups = GetGroupsList(id),
                        GroupDisciplines = new List<GroupDisciplinesVMItem>()
                    });
                return PartialView("_GroupDisciplines", GetModels(id).GroupDisciplines);
            }
            return View("GroupDisciplines", GetModels(id));
        }        

        private SelectList GetGroupsList(string selected = null)
        {
            return new SelectList(unitOfWork.Groups.Get(), "GroupNumber", "GroupNumber", selected);
        }
        

        private GroupDisciplinesVM GetModels(string id)
        {
            var items = unitOfWork.GroupLoads.GetDisciplinesByGroup(id);
            var model = new GroupDisciplinesVM();
            var modelItems = new List<GroupDisciplinesVMItem>();
            model.GroupDisciplines = modelItems;
            if (items.Any())
            {
                model.Groups = new SelectList(unitOfWork.Groups.Get(/*g => g.StudyYear == items.First().StudyYear*/),
                    "GroupNumber", "GroupNumber", id);
            }
            else
            {
                model.Groups = GetGroupsList();
            }
            foreach (GroupLoad groupLoad in items)
            {
                GroupDisciplinesVMItem item = new GroupDisciplinesVMItem
                {
                    ClassType = groupLoad.GroupStudies.GroupClassName,
                    Discipline = groupLoad.Discipline.DisciplineName,
                    TeacherName = groupLoad.Teacher.FullName
                };
                modelItems.Add(item);
            }
            return model;
        }

        // GET: Groups/Create
        public IActionResult Create()
        {
            var model = new StudyGroupVM
            {                
                Specialities = GetSpecialitiesList(),
                Group = new Group()
            };           
            return View("CreateGroup",model);
        }

        // POST: Groups/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(StudyGroupVM groupVM)
        {
            if (ModelState.IsValid)
            {
                unitOfWork.Groups.Insert(groupVM.Group);
                unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            groupVM.Specialities = GetSpecialitiesList(groupVM.Group.SpecialityCode);
            return View("CreateGroup",groupVM);
        }

        // GET: Groups/Edit/5
        public IActionResult Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var group = unitOfWork.Groups.GetByID(id);
            if (group == null)
            {
                return NotFound();
            }
            var model = new StudyGroupVM
            {
                Group = group,
                Specialities = GetSpecialitiesList(group.SpecialityCode)
            };
            return View("EditGroup", model);
        }

        // POST: Groups/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(StudyGroupVM groupVM)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    unitOfWork.Groups.Update(groupVM.Group);
                    unitOfWork.Save();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GroupExists(groupVM.Group.GroupNumber))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            var model = new StudyGroupVM
            {
                Group = groupVM.Group,
                Specialities = GetSpecialitiesList(groupVM.Group.SpecialityCode)
            };
            return View("EditGroup",model);
        }

        // GET: Groups/Delete/5
        public IActionResult Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @group = unitOfWork.Groups.GetByID(id);
            if (@group == null)
            {
                return NotFound();
            }

            return View("DeleteGroup",@group);
        }

        // POST: Groups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(string id)
        {
            var group = unitOfWork.Groups.GetByID(id);           
            unitOfWork.Groups.Delete(group);
            unitOfWork.Save();
            return RedirectToAction(nameof(Index));
        }        

        private SelectList GetSpecialitiesList(string selected = null)
        {
            return new SelectList(unitOfWork.Specialities.Get(), "Code", "NameWithCode", selected);
        }

        private bool GroupExists(string id)
        {
            return unitOfWork.Groups.GetByID(id) != null;
        }
    }
}

TeacherLoadApp/Controllers/PositionsController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TeacherLoad.Core.DataInterfaces;
using TeacherLoad.Core.Models;
using TeacherLoad.Data.Service;

namespace TeacherLoadApp.Controllers
{
    public class PositionsController : Controller
    {
        private readonly IUnitOfWork unitOfWork;

        public PositionsController(TeacherLoadContext context)
        {
            unitOfWork = new UnitOfWork(context);
        }
        // GET: Positions
        public ActionResult Index()
        {
            var positions = unitOfWork.Positions.Get(orderBy: q => q.OrderBy(p => p.PositionName));
            return View("PositionsList", positions);
        }

        public IActionResult Create()
        {
            return View("CreatePosition");
        }

        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Position position)
        {
            if (unitOfWork.Positions.Get(p => p.PositionName == position.PositionName).Any())
            {
                ModelState.AddModelError("PositionName", "Такая должность уже существует!");
            }
            else if (ModelState.IsValid)
            {
                unitOfWork.Positions.Insert(position);
                unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            return View("CreatePosition", position);
        }

        // GET: Groups/Edit/5
        public IActionResult Edit(int id)
        {
            var position = unitOfWork.Positions.GetByID(id);
            if (position == null)
            {
                return NotFound();
            }
            return View("EditPosition", position);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Position position)
        {
            if (id != position.PositionID)
            {
                return NotFound();
            }
            if (unitOfWork.Positions.Get(p => p.PositionName == position.PositionName).Any())
            {
                ModelState.AddModelError("PositionName", "Такая должность уже существует!");
            }
            else if (ModelState.IsValid)
            {
                try
                {
                    unitOfWork.Positions.Update(position);
                    unitOfWork.Save();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (unitOfWork.Positions.GetByID(id) != null)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View("EditPosition", position);
        }

        // GET: Specialities/Delete/5
        public ActionResult Delete(int id)
        {
            var position = unitOfWork.Positions.GetByID(id);
            if (position == null)
            {
                return NotFound();
            }

            return View("DeletePosition", position);
        }

        // POST: Specialities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var position = unitOfWork.Positions.GetByID(id);
            if (position.Teachers.Any())
            {
                ModelState.AddModelError("PositionID", "Нельзя удалять должность, пока на ней работают сотрудники!");
                return View("DeletePosition", position);
            }
            unitOfWork.Positions.Delete(position);
            unitOfWork.Save();
            return RedirectToAction(nameof(Index));
        }
    }
}

TeacherLoadApp/Controllers/UsersController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TeacherLoad.Core.Models;
using TeacherLoadApp.Models;
using System.Linq;
using System.Collections.Generic;

namespace TeacherLoadApp.Controllers
{
    public class UsersController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly RoleManager<IdentityRole> _roleManager;       

        public UsersController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;            
        }
        [HttpGet]
        public IActionResult Register()
        {
            UserWithRoleVM model = new UserWithRoleVM
            {               
                AllRoles = _roleManager.Roles.ToList()
            };
            return View("CreateUser",model);
        }
        [HttpPost]
        public async Task<IActionResult> Register(UserWithRoleVM model)
        {
            if (ModelState.IsValid)
            {
                ApplicationUser user = new ApplicationUser {  UserName = model.UserName };
                // добавляем пользователя
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {                   
                    await UpdateUserRoles(user, model.UserRoles.ToList());
                    return RedirectToAction("UsersList");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(model);
        }
        [HttpGet]        
        public IActionResult Login(string returnUrl = null)
        {
            return View(new LoginVM { ReturnUrl = returnUrl });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginVM model)
        {
            if (ModelState.IsValid)
            {
                // установка куки
                //var user = _userManager.Users.Single(u => u.UserName == model.Username);
                //AuthenticationProperties authProp = new AuthenticationProperties();
                //authProp.ExpiresUtc = DateTime.UtcNow.AddMinutes(5);
                //authProp.IsPersistent = model.RememberMe;
                //await _signInManager.SignInAsync(user, authProp);
                var result =
                    await _signInManager.PasswordSignInAsync(model.Username, model.Password, model.RememberMe, false);
                if (result.Succeeded)
                {
                    // проверяем, принадлежит ли URL приложению
                    if (!string.IsNullOrEmpty(model.ReturnUrl) && Url.IsLocalUrl(model.ReturnUrl))
                    {
                        return Redirect(model.ReturnUrl);
                    }
                    else
                    {
                        return RedirectToAction("Index", "Home");
                    }
                }
                else
                {
                    ModelState.AddModelError("WrongData", "Неправильный логин и (или) пароль");
                }
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Logoff()
        {
            // удаляем аутентификационные куки
            await _signInManager.SignOutAsync();
            return RedirectToAction("Login");
        }
        
        public ActionResult UsersList()
        {       
            var usersWithRole = new List<UserWithRoleVM>();
            
            foreach(ApplicationUser user in _userManager.Users.ToList())
            {
                usersWithRole.Add(new UserWithRoleVM
                {
                    UserId = user.Id,
                    UserName = user.UserName,
                    UserRoles = _userManager.GetRolesAsync(user).Result                    
                });
            }
            return View("UsersList", usersWithRole);
        }

        public async Task<ActionResult> Edit(string id)
        {
            ApplicationUser user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            UserWithRoleVM model = new UserWithRoleVM
            {
                UserId = user.Id,
                UserName = user.UserName,
                UserRoles = _userManager.GetRolesAsync(user).Result,
                AllRoles = _roleManager.Roles.ToList()
            };
            return View("EditUser",model);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(string UserId, List<string> UserRoles)
        {
            ApplicationUser user = await _userManager.FindByIdAsync(UserId);
            if (user != null)
            {
                await UpdateUserRoles(user, UserRoles);
                return RedirectToAction("UsersList");
            }
            return NotFound();
        }

        /*[HttpPost]*/
        public async Task<ActionResult> Delete(string id)
        {
            ApplicationUser user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                await _userManager.DeleteAsync(user);
            }
            return RedirectToAction("UsersList");
        }

        public async Task UpdateUserRoles(ApplicationUser user, List<string> roles)
        {
            var userRoles = await _userManager.GetRolesAsync(user);
            // получаем список ролей, которые были добавлены
            var addedRoles = roles.Except(userRoles);
            // получаем роли, которые были удалены
            var removedRoles = userRoles.Except(roles);

            await _userManager.AddToRolesAsync(user, addedRoles);
            await _userManager.RemoveFromRolesAsync(user, removedRoles);
        }
    }
}

TeacherLoadApp/Views/Shared/ButtonPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<TeacherLoad.Core.Models.ApplicationUser> SignInManager
@inject UserManager<TeacherLoad.Core.Models.ApplicationUser> UserManager

@if (User.IsInRole("Администратор") || User.IsInRole("Оператор"))
{
<div style="float: right;">
    <a class="btn-sm btn-success" asp-action="Edit" asp-route-id="@ViewData["id"]">
        <span class="btn-label"><i class="glyphicon glyphicon-pencil"></i></span>
        Изменить
    </a>
    <a style="margin-left: 5px;" class="btn-sm btn-danger" asp-action="Delete" asp-route-id="@ViewData["id"]">
        <span class="btn-label"><i class="glyphicon glyphicon-trash"></i></span>
        Удалить
    </a>
</div>
}

TeacherLoadApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<TeacherLoad.Core.Models.ApplicationUser> SignInManager
@inject UserManager<TeacherLoad.Core.Models.ApplicationUser> UserManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />        
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
        <link href="https://fonts.googleapis.com/css?family=Coda" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    </environment>
</head>
<body>
    @if (SignInManager.IsSignedIn(User))
    {
        <nav class="navbar navbar-inverse navbar-fixed-top" style="background-color: #265C94; font-family: 'Coda', cursive;">
            <div style="margin-right: 8%">
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav menu-nav" role="menu">
                        <li class="nav-item">
                            @Html.ActionLink("Домой", "Index", "Home")
                        </li>
                        @if (User.IsInRole("Администратор") || User.IsInRole("Оператор"))
                        {
                            <li class="nav-item dropdown">
                                <a class="navbar-link dropdown-toggle" href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                    Справочники<b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">

                                    <li>@Html.ActionLink("Виды групповых занятий", "Index", "GroupStudies")</li>
                                    <li>@Html.ActionLink("Виды индивидуальных занятий", "Index", "IndividualStudies")</li>
                                    <li>@Html.ActionLink("Специальности", "Index", "Specialities")</li>
                                    <li>@Html.ActionLink("Дисциплины", "Index", "Disciplines")</li>
                                    <li>@Html.ActionLink("Должности", "Index", "Positions")</li>
                                    @if (User.IsInRole("Администратор"))
                                    {
                                        <li>@Html.ActionLink("Пользователи", "UsersList", "Users")</li>
                                    }
                                    <li><hr /></li>
                                    <li>@Html.ActionLink("Преподаватели", "Index", "Teachers")</li>
                                    <li>@Html.ActionLink("Учебные группы", "Index", "Groups")</li>

                                </ul>
                            </li>
                        }
                        @if (User.IsInRole("Администратор") || User.IsInRole("Оператор"))
                        {
                            <li class="nav-item dropdown">
                                <a class="navbar-link dropdown-toggle" href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                   Учет преподавательской нагрузки<b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Групповая нагрузка", "Index", "GroupLoads")</li>
                                    <li>@Html.ActionLink("Индивидуальная нагрузка", "Index", "PersonalLoads")</li>
                                </ul>
                            </li>
                        }
                        @if (!User.IsInRole("Оператор"))
                        {
                            <li class="nav-item dropdown">
                                <a class="navbar-link dropdown-toggle" href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                    Запросы<b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Все дисциплины для указанной группы", "GroupDisciplines", "Groups")</li>
                                    <li>@Html.ActionLink("Преподаватели с выбранным видом занятий", "Index", "PersonalLoads")</li>
                                    <li>@Html.ActionLink("Групповая нагрузка преподавателя", "TeachersGroupLoad", "GroupLoads")</li>
                                </ul>
                            </li>
                            <li class="nav-item">
                                @Html.ActionLink("Сформировать отчет", "ShowReport", "Home")
                            </li>
                        }
                            <li class="nav-item">
                                <a asp-area="Identity" title="Manage">@UserManager.GetUserName(User)</a>
                            </li>
                            <li class="nav-item">
                                <form method="post" asp-controller="Users" asp-action="Logoff">
                                    <button class="btn-logoff" type="submit">Выйти</button>
                                </form>
                            </li>
                        </ul>
                </div>
            </div>
        </nav>
    }
    <partial name="_CookieConsentPartial" />

    <div class="container body-content">       
        @RenderBody()        
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>        
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

TeacherLoadApp/Views/Shared/_NotificationsPartial.cshtml
@model IEnumerable<string>
@foreach (var notification in Model)
{
    <div class="alert alert-success" style="margin-top: 10px;" role="alert">
        @notification
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
    </div>
}